import React,{useEffect,useRef,useState} from 'react';
import {supabase} from '../lib/supabaseClient';import {useAuth} from '../lib/AuthContext';import {hasAnyRole} from '../lib/roles';import {VoiceMicButton} from '../components/VoiceMicButton';import {uploadFile} from '../lib/queries';
const format=d=>new Date(d).toLocaleString('vi-VN',{dateStyle:'short',timeStyle:'short'});
export default function CompanyFeedScreen(){const{profile}=useAuth(),director=hasAnyRole(profile,['owner','admin']);const[tab,setTab]=useState('announcement'),[posts,setPosts]=useState([]),[show,setShow]=useState(false),[error,setError]=useState('');
 const load=async()=>{const r=await supabase.from('company_feed_posts').select('*,company_feed_comments(*),company_feed_reactions(*),company_announcement_acks(*)').is('deleted_at',null).order('pinned',{ascending:false}).order('created_at',{ascending:false});if(r.error)throw r.error;setPosts(r.data||[])};
 useEffect(()=>{load().catch(e=>setError(e.message));const ch=supabase.channel('company-feed-live').on('postgres_changes',{event:'*',schema:'public',table:'company_feed_posts'},()=>load().catch(()=>{})).on('postgres_changes',{event:'*',schema:'public',table:'company_feed_comments'},()=>load().catch(()=>{})).subscribe();return()=>supabase.removeChannel(ch)},[]);
 const visible=posts.filter(p=>p.post_type===tab);const friendly=error&&(error.includes('does not exist')||error.includes('schema cache'))?'Bảng tin đang chờ kích hoạt dữ liệu trên Supabase.':error;
 return <div className="company-feed"><header><div><small>CHUYỆN NHÀ SUMI</small><h1>Bảng tin SUMI</h1><p>Thông báo quan trọng và những khoảnh khắc mỗi ngày.</p></div><span>🥐</span></header><nav><button className={tab==='announcement'?'active':''} onClick={()=>setTab('announcement')}>📢 Công ty</button><button className={tab==='daily'?'active':''} onClick={()=>setTab('daily')}>📸 Nhật ký SUMI</button></nav>{(tab==='daily'||director)&&<button className="feed-create" onClick={()=>setShow(!show)}>＋ {tab==='announcement'?'ĐĂNG THÔNG BÁO':'CHIA SẺ HÔM NAY'}</button>}{show&&<Composer type={tab} profile={profile} onDone={()=>{setShow(false);load()}}/>}{visible.length===0?<div className="feed-empty">{tab==='announcement'?'Chưa có thông báo công ty.':'Hãy chia sẻ bức ảnh đầu tiên hôm nay.'}</div>:visible.map(p=><Post key={p.id} post={p} profile={profile} director={director} onChange={load}/>) }{friendly&&<div className="feed-error">{friendly}</div>}</div>}

function Composer({type,profile,onDone}){const[title,setTitle]=useState(''),[body,setBody]=useState(''),[severity,setSeverity]=useState('normal'),[media,setMedia]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const ref=useRef();
 const pick=async files=>{setBusy(true);try{const added=[];for(const f of Array.from(files).slice(0,4))added.push(await uploadFile(f,`company-feed/${profile.id}`));setMedia(x=>[...x,...added])}catch(e){setError(e.message)}finally{setBusy(false)}};
 const send=async()=>{if(!body.trim())return setError('Hãy nhập hoặc nói một nội dung.');setBusy(true);try{const r=await supabase.from('company_feed_posts').insert({author_id:profile.id,author_name:profile.full_name,post_type:type,title:type==='announcement'?title.trim()||'Thông báo công ty':null,body:body.trim(),media:media.length?media:null,severity:type==='announcement'?severity:'normal',pinned:type==='announcement'&&severity!=='normal',safe_for_company:true});if(r.error)throw r.error;onDone()}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <section className="feed-composer">{type==='announcement'&&<><label>Tiêu đề<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ví dụ: Chủ nhật cúp điện"/></label><div className="feed-severity">{[['normal','Bình thường'],['important','Quan trọng'],['urgent','Khẩn cấp']].map(x=><button className={severity===x[0]?'active':''} key={x[0]} onClick={()=>setSeverity(x[0])}>{x[1]}</button>)}</div></>}<label>Nội dung<div className="feed-voice"><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Viết hoặc bấm Nói..."/><VoiceMicButton onTranscript={setBody}/></div></label><button className="feed-media" onClick={()=>ref.current?.click()}>📷 Thêm ảnh hoặc Vlog ngắn</button><input ref={ref} hidden type="file" accept="image/*,video/*" multiple onChange={e=>pick(e.target.files)}/>{media.length>0&&<div className="feed-media-count">Đã chọn {media.length} tệp</div>}<p className="feed-safety">🔒 Không đăng giá, thông tin trường học hoặc dữ liệu khách hàng nhạy cảm.</p><button className="feed-publish" disabled={busy} onClick={send}>{busy?'ĐANG ĐĂNG...':'ĐĂNG LÊN BẢNG TIN'}</button>{error&&<div className="feed-error">{error}</div>}</section>}

function Post({post,profile,director,onChange}){const[draft,setDraft]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);const comments=(post.company_feed_comments||[]).filter(c=>!c.deleted_at),reactions=post.company_feed_reactions||[],acked=(post.company_announcement_acks||[]).some(a=>a.profile_id===profile.id),liked=reactions.some(r=>r.profile_id===profile.id);
 const speak=()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`${post.title||''}. ${post.body}`);u.lang='vi-VN';speechSynthesis.speak(u)};
 const ack=async()=>{await supabase.from('company_announcement_acks').upsert({post_id:post.id,profile_id:profile.id});onChange()};
 const like=async()=>{liked?await supabase.from('company_feed_reactions').delete().eq('post_id',post.id).eq('profile_id',profile.id):await supabase.from('company_feed_reactions').insert({post_id:post.id,profile_id:profile.id});onChange()};
 const comment=async()=>{if(!draft.trim())return;setBusy(true);const r=await supabase.from('company_feed_comments').insert({post_id:post.id,author_id:profile.id,author_name:profile.full_name,body:draft.trim()});setBusy(false);if(!r.error){setDraft('');onChange()}};
 return <article className={`feed-post ${post.post_type} ${post.severity}`}><div className="feed-post-head"><span className="feed-avatar">{post.post_type==='announcement'?'📢':'👤'}</span><div><strong>{post.author_name}</strong><small>{format(post.created_at)}{post.pinned?' · ĐÃ GHIM':''}</small></div>{(post.author_id===profile.id||director)&&<button onClick={async()=>{await supabase.from('company_feed_posts').update({deleted_at:new Date().toISOString()}).eq('id',post.id);onChange()}}>•••</button>}</div>{post.title&&<h2>{post.title}</h2>}<p className="feed-body">{post.body}</p>{post.media?.length>0&&<div className="feed-gallery">{post.media.map((m,i)=>m.type?.startsWith('video/')?<video key={i} src={m.url} controls/>:<img key={i} src={m.url} alt={m.name||'Ảnh bảng tin'}/>)}</div>}<div className="feed-tools"><button onClick={like}>{liked?'❤️':'🤍'} {reactions.length}</button><button onClick={()=>setOpen(!open)}>💬 {comments.length}</button><button onClick={speak}>🔊 Nghe</button></div>{post.post_type==='announcement'&&!acked&&<button className="feed-ack" onClick={ack}>✓ TÔI ĐÃ HIỂU</button>}{post.post_type==='announcement'&&acked&&<div className="feed-acked">✓ Bạn đã xác nhận</div>}{open&&<div className="feed-comments">{comments.map(c=><div key={c.id}><b>{c.author_name}</b><span>{c.body}</span></div>)}<div className="feed-comment-box"><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Viết bình luận..."/><VoiceMicButton onTranscript={setDraft}/><button disabled={busy} onClick={comment}>Gửi</button></div></div>}</article>}
