import React,{useEffect,useRef,useState} from 'react';
import {supabase} from '../lib/supabaseClient';import {useAuth} from '../lib/AuthContext';import {hasAnyRole} from '../lib/roles';import {VoiceMicButton} from '../components/VoiceMicButton';import UserAvatar from '../components/UserAvatar';import {uploadFile} from '../lib/queries';import {toWebSafeImage} from '../lib/imageConvert';import {notifyCompany, requestNotificationPermission, playAlertSound} from '../lib/alarmSound';
import {subscribeToBroadcast, BroadcastEvents, broadcastEvent} from '../lib/realtimeSync';
import '../feed-media-fixes.css';
const format=d=>new Date(d).toLocaleString('vi-VN',{dateStyle:'short',timeStyle:'short'});
export default function CompanyFeedScreen(){const{profile}=useAuth(),legacyDirector=hasAnyRole(profile,['owner','admin']);const[director,setDirector]=useState(legacyDirector),[tab,setTab]=useState('announcement'),[posts,setPosts]=useState([]),[authors,setAuthors]=useState({}),[show,setShow]=useState(false),[error,setError]=useState('');
 const load=async()=>{const r=await supabase.from('company_feed_posts').select('*,company_feed_comments(*),company_feed_reactions(*),company_announcement_acks(*)').is('deleted_at',null).order('pinned',{ascending:false}).order('created_at',{ascending:false});if(r.error)throw r.error;const rows=r.data||[];setPosts(rows);const ids=[...new Set([
   ...rows.map(x=>x.author_id),
   ...rows.flatMap(x=>(x.company_feed_reactions||[]).map(r=>r.profile_id)),
   ...rows.flatMap(x=>(x.company_announcement_acks||[]).map(a=>a.profile_id)),
  ].filter(Boolean))];if(ids.length){const p=await supabase.from('profiles').select('id,full_name,avatar_path').in('id',ids);if(!p.error)setAuthors(Object.fromEntries((p.data||[]).map(x=>[x.id,x])))}};
// Bấm vào tin nhắn thông báo -> cuộn tới đúng bài đăng đó và làm nổi bật.
 // Thử lại vài lần vì danh sách bài có thể chưa tải xong lúc vừa chuyển trang.
 useEffect(()=>{const go=e=>{const id=e.detail?.entityId;if(!id)return;let n=0;const tim=()=>{const el=document.getElementById(`feed-post-${id}`);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});el.classList.add('feed-post-focus');setTimeout(()=>el.classList.remove('feed-post-focus'),2600);return}if(++n<20)setTimeout(tim,250)};tim()};window.addEventListener('sumi-open-feed',go);return()=>window.removeEventListener('sumi-open-feed',go)},[]);
 useEffect(()=>{requestNotificationPermission();supabase.rpc('is_business_director').then(({data})=>setDirector(legacyDirector||data===true));load().catch(e=>setError(e.message));const ch=supabase.channel('company-feed-live').on('postgres_changes',{event:'INSERT',schema:'public',table:'company_feed_posts'},(payload)=>{console.log('[Feed] New post via DB change!',payload);if(payload.new?.post_type==='announcement'){console.log('[Feed] Playing sound for new announcement...');playAlertSound().catch(err=>console.error('[Feed] Sound error:',err))}load().catch(()=>{})}).on('postgres_changes',{event:'*',schema:'public',table:'company_feed_comments'},()=>load().catch(()=>{})).subscribe();const unsubBroadcast=subscribeToBroadcast(BroadcastEvents.FEED_POST_CREATED,()=>{console.log('[Feed] Announcement broadcast received!');playAlertSound().catch(err=>console.error('[Feed] Broadcast sound error:',err));load().catch(()=>{})});return()=>{supabase.removeChannel(ch);unsubBroadcast()}},[legacyDirector]);
 const visible=posts.filter(p=>p.post_type===tab);const friendly=error&&(error.includes('does not exist')||error.includes('schema cache'))?'Bảng tin đang chờ kích hoạt dữ liệu trên Supabase.':error;
 return <div className="company-feed"><header><div><small>CHUYỆN NHÀ SUMI</small><h1>Bảng tin SUMI</h1><p>Thông báo quan trọng và những khoảnh khắc mỗi ngày.</p></div><span>🥐</span></header><nav><button className={tab==='announcement'?'active':''} onClick={()=>setTab('announcement')}>📢 Công ty</button><button className={tab==='daily'?'active':''} onClick={()=>setTab('daily')}>📸 Nhật ký SUMI</button></nav>{(tab==='daily'||director)&&<button className="feed-create" onClick={()=>setShow(!show)}>＋ {tab==='announcement'?'ĐĂNG THÔNG BÁO':'CHIA SẺ HÔM NAY'}</button>}{show&&<Composer type={tab} profile={profile} onDone={()=>{setShow(false);load()}}/>}{visible.length===0?<div className="feed-empty">{tab==='announcement'?'Chưa có thông báo công ty.':'Hãy chia sẻ bức ảnh đầu tiên hôm nay.'}</div>:visible.map(p=><Post key={p.id} post={p} author={authors[p.author_id]||(p.author_id===profile.id?profile:null)} profiles={authors} profile={profile} director={director} onChange={load}/>) }{friendly&&<div className="feed-error">{friendly}</div>}</div>}

function Composer({type,profile,onDone}){const[title,setTitle]=useState(''),[body,setBody]=useState(''),[severity,setSeverity]=useState('normal'),[media,setMedia]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const ref=useRef();
 const pick=async files=>{setBusy(true);setError('');try{const added=[];for(const original of Array.from(files).slice(0,4)){const f=original.type?.startsWith('image/')?await toWebSafeImage(original):original;if(/\.(heic|heif)$/i.test(f.name||'')||/heic|heif/i.test(f.type||''))throw new Error('Ảnh HEIC chưa chuyển được sang JPG nên chưa thể đăng.');added.push(await uploadFile(f,`company-feed/${profile.id}`))}setMedia(x=>[...x,...added])}catch(e){setError(e.message||'Không thể xử lý ảnh này. Hãy thử lại.')}finally{setBusy(false)}};
 const send=async()=>{if(!body.trim())return setError('Hãy nhập hoặc nói một nội dung.');setBusy(true);try{const r=await supabase.from('company_feed_posts').insert({author_id:profile.id,author_name:profile.full_name,post_type:type,title:type==='announcement'?title.trim()||'Thông báo công ty':null,body:body.trim(),media:media.length?media:null,severity:type==='announcement'?severity:'normal',pinned:type==='announcement'&&severity!=='normal',safe_for_company:true});if(r.error)throw r.error;if(type==='announcement'){const title_text=title.trim()||'Thông báo công ty';const body_text=body.trim();console.log('[Composer] Broadcasting announcement...');await notifyCompany(title_text,body_text,severity);await broadcastEvent(BroadcastEvents.FEED_POST_CREATED,{title:title_text,body:body_text,severity,author:profile.full_name});console.log('[Composer] Broadcast sent!')}onDone()}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <section className="feed-composer">{type==='announcement'&&<><label>Tiêu đề<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ví dụ: Chủ nhật cúp điện"/></label><div className="feed-severity">{[['normal','Bình thường'],['important','Quan trọng'],['urgent','Khẩn cấp']].map(x=><button className={severity===x[0]?'active':''} key={x[0]} onClick={()=>setSeverity(x[0])}>{x[1]}</button>)}</div></>}<label>Nội dung<div className="feed-voice"><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Viết hoặc bấm Nói..."/><VoiceMicButton onTranscript={setBody}/></div></label><button className="feed-media" onClick={()=>ref.current?.click()}>📷 Thêm ảnh hoặc Vlog ngắn</button><input ref={ref} hidden type="file" accept="image/*,video/*" multiple onChange={e=>pick(e.target.files)}/>{media.length>0&&<div className="feed-media-count">Đã chọn {media.length} tệp</div>}<p className="feed-safety">🔒 Không đăng giá, thông tin trường học hoặc dữ liệu khách hàng nhạy cảm.</p><button className="feed-publish" disabled={busy} onClick={send}>{busy?'ĐANG ĐĂNG...':'ĐĂNG LÊN BẢNG TIN'}</button>{error&&<div className="feed-error">{error}</div>}</section>}

function SafeMedia({media}){const[src,setSrc]=useState(media.url),[loading,setLoading]=useState(/\.(heic|heif)(\?|$)/i.test(media.url||'')||/heic|heif/i.test(media.type||''));useEffect(()=>{let objectUrl='',alive=true;const heic=/\.(heic|heif)(\?|$)/i.test(media.url||'')||/heic|heif/i.test(media.type||'');if(!heic){setSrc(media.url);setLoading(false);return undefined}(async()=>{try{const response=await fetch(media.url);if(!response.ok)throw new Error('download');const blob=await response.blob();const file=new File([blob],media.name||'anh.heic',{type:media.type||blob.type||'image/heic'});const jpg=await toWebSafeImage(file);objectUrl=URL.createObjectURL(jpg);if(alive)setSrc(objectUrl)}catch{if(alive)setSrc('')}finally{if(alive)setLoading(false)}})();return()=>{alive=false;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[media.url,media.name,media.type]);if(loading)return <div className="feed-media-loading">Đang mở ảnh...</div>;if(!src)return <div className="feed-media-error">Ảnh chưa mở được</div>;return <img src={src} alt={media.name||'Ảnh bảng tin'} onError={()=>setSrc('')}/>}

function Post({post,author,profiles,profile,director,onChange}){const[draft,setDraft]=useState(''),[open,setOpen]=useState(false),[menu,setMenu]=useState(false),[busy,setBusy]=useState(false),[showLikers,setShowLikers]=useState(false),[showViewers,setShowViewers]=useState(false);const comments=(post.company_feed_comments||[]).filter(c=>!c.deleted_at),reactions=post.company_feed_reactions||[],acks=post.company_announcement_acks||[],acked=acks.some(a=>a.profile_id===profile.id),liked=reactions.some(r=>r.profile_id===profile.id);
 const nameFor=id=>profiles?.[id]?.full_name||(id===profile.id?profile.full_name:'Nhân viên');
 const speak=()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`${post.title||''}. ${post.body}`);u.lang='vi-VN';speechSynthesis.speak(u)};
 const ack=async()=>{await supabase.from('company_announcement_acks').upsert({post_id:post.id,profile_id:profile.id});onChange()};
 const like=async()=>{liked?await supabase.from('company_feed_reactions').delete().eq('post_id',post.id).eq('profile_id',profile.id):await supabase.from('company_feed_reactions').insert({post_id:post.id,profile_id:profile.id});onChange()};
 const comment=async()=>{if(!draft.trim())return;setBusy(true);const r=await supabase.from('company_feed_comments').insert({post_id:post.id,author_id:profile.id,author_name:profile.full_name,body:draft.trim()});setBusy(false);if(!r.error){setDraft('');onChange()}};
 const remove=async()=>{setBusy(true);const r=await supabase.from('company_feed_posts').update({deleted_at:new Date().toISOString()}).eq('id',post.id);setBusy(false);if(!r.error)onChange()};
 return <article id={`feed-post-${post.id}`} className={`feed-post ${post.post_type} ${post.severity}`}><div className="feed-post-head"><span className="feed-avatar">{post.post_type==='announcement'?'📢':<UserAvatar profile={author||{full_name:post.author_name}} size={43}/>}</span><div><strong>{post.author_name}</strong><small>{format(post.created_at)}{post.pinned?' · ĐÃ GHIM':''}</small></div>{(post.author_id===profile.id||director)&&<button aria-label="Mở tùy chọn bài viết" onClick={()=>setMenu(!menu)}>•••</button>}</div>{menu&&<div className="feed-post-menu"><p>Bạn muốn làm gì với bài viết này?</p><button onClick={()=>setMenu(false)}>GIỮ LẠI</button><button className="delete" disabled={busy} onClick={remove}>{busy?'ĐANG XÓA...':'🗑️ XÓA BÀI VIẾT'}</button></div>}{post.title&&<h2>{post.title}</h2>}<p className="feed-body">{post.body}</p>{post.media?.length>0&&<div className="feed-gallery">{post.media.map((m,i)=>m.type?.startsWith('video/')?<video key={i} src={m.url} controls/>:<SafeMedia key={i} media={m}/>)}</div>}<div className="feed-tools"><button onClick={like}>{liked?'❤️':'🤍'} {reactions.length}</button>{director&&reactions.length>0&&<button onClick={()=>setShowLikers(v=>!v)} style={{fontSize:12,color:'var(--text-muted)'}}>👀 ds thả tim</button>}<button onClick={()=>setOpen(!open)}>💬 {comments.length}</button><button onClick={speak}>🔊 Nghe</button></div>{director&&showLikers&&<div className="feed-comments" style={{padding:'6px 10px'}}>{reactions.length===0?<span style={{color:'var(--text-muted)',fontSize:13}}>Chưa ai thả tim.</span>:reactions.map(r=><div key={r.profile_id} style={{fontSize:13,color:'var(--text-secondary)'}}>❤️ {nameFor(r.profile_id)}</div>)}</div>}{post.post_type==='announcement'&&!acked&&<button className="feed-ack" onClick={ack}>✓ TÔI ĐÃ HIỂU</button>}{post.post_type==='announcement'&&acked&&<div className="feed-acked">✓ Bạn đã xác nhận</div>}{post.post_type==='announcement'&&director&&<button onClick={()=>setShowViewers(v=>!v)} style={{fontSize:12,color:'var(--text-muted)',background:'none',border:'none',cursor:'pointer',textAlign:'left'}}>👁 Đã xem: {acks.length} người {showViewers?'▲':'▼'}</button>}{post.post_type==='announcement'&&director&&showViewers&&<div className="feed-comments" style={{padding:'6px 10px'}}>{acks.length===0?<span style={{color:'var(--text-muted)',fontSize:13}}>Chưa ai xác nhận đã xem.</span>:acks.map(a=><div key={a.profile_id} style={{fontSize:13,color:'var(--text-secondary)'}}>✓ {nameFor(a.profile_id)}</div>)}</div>}{open&&<div className="feed-comments">{comments.map(c=><div key={c.id}><b>{c.author_name}</b><span>{c.body}</span></div>)}<div className="feed-comment-box"><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Viết bình luận..."/><VoiceMicButton onTranscript={setDraft}/><button disabled={busy} onClick={comment}>Gửi</button></div></div>}</article>}
