import React,{useEffect,useRef,useState} from 'react';
import {supabase} from '../lib/supabaseClient';
import {useAuth} from '../lib/AuthContext';
import {hasAnyRole} from '../lib/roles';
import {VoiceMicButton} from '../components/VoiceMicButton';
import {uploadPhoto} from '../lib/queries';
import {toWebSafeImage} from '../lib/imageConvert';

const money=n=>Number(n||0).toLocaleString('vi-VN')+'đ';
const nowLocal=()=>{const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,16)};
const labels={pending_director:'Chờ Giám đốc',pending_accounting:'Chờ Kế toán',recorded:'Đã ghi sổ',paid:'Đã chi',rejected:'Từ chối',cancelled:'Đã hủy'};

export default function FinanceRequestsScreen(){
 const {profile}=useAuth(),director=hasAnyRole(profile,['owner','admin']),finance=hasAnyRole(profile,['owner','admin','accountant','cashier']);
 const[tab,setTab]=useState('expense'),[expenses,setExpenses]=useState([]),[advances,setAdvances]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{setError('');try{const[e,a]=await Promise.all([supabase.from('expense_claims').select('*').order('created_at',{ascending:false}),supabase.from('salary_advance_requests').select('*').order('created_at',{ascending:false})]);if(e.error)throw e.error;if(a.error)throw a.error;setExpenses(e.data||[]);setAdvances(a.data||[])}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[profile?.id]);
 const act=async(fn,args)=>{setBusy(true);try{const r=await supabase.rpc(fn,args);if(r.error)throw r.error;await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const friendly=error&&(error.includes('does not exist')||error.includes('schema cache')||error.includes('expense_claims'))?'Chức năng đang chờ kích hoạt dữ liệu tài chính trên Supabase.':error;
 return <div className="finance-request-page"><header><small>CHI TIÊU MINH BẠCH</small><h1>Chi & tạm ứng</h1><p>Báo nhanh bằng chữ, giọng nói hoặc ảnh. Hệ thống tự xác định khoản cần Giám đốc duyệt.</p></header><nav><button className={tab==='expense'?'active':''} onClick={()=>setTab('expense')}>🧾 Khoản chi</button><button className={tab==='advance'?'active':''} onClick={()=>setTab('advance')}>💵 Tạm ứng lương</button></nav>{tab==='expense'?<><ExpenseForm onDone={load}/><Rows rows={expenses} kind="expense" director={director} finance={finance} busy={busy} act={act}/></>:<><AdvanceForm onDone={load}/><Rows rows={advances} kind="advance" director={director} finance={finance} busy={busy} act={act}/></>}{friendly&&<div className="finance-error">{friendly}</div>}</div>
}

function ExpenseForm({onDone}){const[a,setA]=useState(''),[desc,setDesc]=useState(''),[note,setNote]=useState(''),[order,setOrder]=useState(''),[when,setWhen]=useState(nowLocal()),[receipt,setReceipt]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const ref=useRef();
 const pick=async f=>{if(!f)return;setBusy(true);try{const safe=await toWebSafeImage(f),url=await uploadPhoto(safe,`expense_${Date.now()}`);setReceipt({url,name:safe.name,type:safe.type})}catch(e){setError(e.message)}finally{setBusy(false)}};
 const send=async()=>{if(!a||!desc.trim())return setError('Nhập số tiền và nội dung chi.');setBusy(true);try{const r=await supabase.rpc('submit_expense_claim',{p_amount:Number(a),p_description:desc.trim(),p_note:note.trim()||null,p_related_order_code:order.trim()||null,p_receipt_attachments:receipt?[receipt]:null,p_occurred_at:new Date(when).toISOString()});if(r.error)throw r.error;setA('');setDesc('');setNote('');setOrder('');setReceipt(null);setWhen(nowLocal());await onDone()}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <section className="finance-form"><Title icon="🧾" title="Báo một khoản chi" text="Người chi và nơi làm việc được lấy tự động."/><Field name="Số tiền"><input type="number" inputMode="numeric" value={a} onChange={e=>setA(e.target.value)} placeholder="Ví dụ: 120000"/></Field><Field name="Nội dung chi"><Voice value={desc} set={setDesc} placeholder="Ví dụ: mua thêm đá lạnh cho đơn gấp"/></Field><Field name="Ngày giờ phát sinh"><input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/></Field><Field name="Ghi chú"><Voice value={note} set={setNote} placeholder="Ví dụ: Sếp đưa tiền mặt; mượn từ thu ngân"/></Field><Field name="Mã đơn nếu có"><input value={order} onChange={e=>setOrder(e.target.value)} placeholder="Không bắt buộc"/></Field><button className="receipt-button" onClick={()=>ref.current?.click()}>📷 {receipt?'Đã có ảnh chứng từ':'Chụp hóa đơn/chứng từ'}</button><input ref={ref} hidden type="file" accept="image/*" capture="environment" onChange={e=>pick(e.target.files?.[0])}/><button className="finance-submit" disabled={busy} onClick={send}>{busy?'ĐANG LƯU...':'GỬI KHOẢN CHI'}</button>{error&&<p className="finance-inline-error">{error}</p>}</section>}

function AdvanceForm({onDone}){const[a,setA]=useState(''),[reason,setReason]=useState(''),[needed,setNeeded]=useState(new Date().toISOString().slice(0,10)),[method,setMethod]=useState('cash'),[busy,setBusy]=useState(false),[error,setError]=useState('');const send=async()=>{if(!a||!reason.trim())return setError('Nhập số tiền và lý do tạm ứng.');setBusy(true);try{const r=await supabase.rpc('submit_salary_advance',{p_amount:Number(a),p_reason:reason.trim(),p_needed_on:needed,p_payment_method:method});if(r.error)throw r.error;setA('');setReason('');await onDone()}catch(e){setError(e.message)}finally{setBusy(false)}};return <section className="finance-form"><Title icon="💵" title="Xin tạm ứng lương" text="Mọi yêu cầu đều cần Giám đốc duyệt."/><Field name="Số tiền"><input type="number" inputMode="numeric" value={a} onChange={e=>setA(e.target.value)} placeholder="Ví dụ: 1000000"/></Field><Field name="Lý do"><Voice value={reason} set={setReason} placeholder="Nói hoặc nhập lý do cần tạm ứng"/></Field><Field name="Ngày cần nhận"><input type="date" value={needed} onChange={e=>setNeeded(e.target.value)}/></Field><div className="finance-method"><button className={method==='cash'?'active':''} onClick={()=>setMethod('cash')}>💴 Tiền mặt</button><button className={method==='bank_transfer'?'active':''} onClick={()=>setMethod('bank_transfer')}>🏦 Chuyển khoản</button></div><button className="finance-submit" disabled={busy} onClick={send}>{busy?'ĐANG GỬI...':'GỬI GIÁM ĐỐC DUYỆT'}</button>{error&&<p className="finance-inline-error">{error}</p>}</section>}

const Title=({icon,title,text})=><div className="finance-form-title"><span>{icon}</span><div><h2>{title}</h2><p>{text}</p></div></div>;
const Field=({name,children})=><label>{name}{children}</label>;
const Voice=({value,set,placeholder})=><div className="voice-field"><textarea value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/><VoiceMicButton onTranscript={set}/></div>;

function Rows({rows,kind,director,finance,busy,act}){return <section className="finance-list"><div className="finance-list-title"><h2>{kind==='expense'?'Các khoản đã báo':'Yêu cầu tạm ứng'}</h2><b>{rows.filter(x=>x.status.startsWith('pending')).length} chờ</b></div>{rows.length===0?<p className="finance-empty">Chưa có dữ liệu.</p>:rows.map(r=><article key={r.id} className={`finance-row ${r.status}`}><div className="finance-row-top"><div><strong>{kind==='expense'?r.description:r.employee_name}</strong><small>{kind==='expense'?r.claimant_name:r.reason}</small></div><b>{money(r.amount)}</b></div><div className="finance-meta"><span>{labels[r.status]}</span><time>{new Date(r.occurred_at||r.created_at).toLocaleString('vi-VN')}</time></div>{kind==='expense'&&r.note&&<p>Ghi chú: {r.note}</p>}{kind==='expense'&&r.approval_reason&&<em>⚠ {r.approval_reason}</em>}{kind==='expense'&&r.receipt_attachments?.[0]?.url&&<a href={r.receipt_attachments[0].url} target="_blank" rel="noreferrer">📷 Xem chứng từ</a>}{r.status==='pending_director'&&director&&<div className="finance-actions"><button onClick={()=>act(kind==='expense'?'review_expense_claim':'review_salary_advance',{p_id:r.id,p_approve:false,p_note:null})}>Từ chối</button><button onClick={()=>act(kind==='expense'?'review_expense_claim':'review_salary_advance',{p_id:r.id,p_approve:true,p_note:null})}>Duyệt</button></div>}{r.status==='pending_accounting'&&finance&&<button className="finance-record" disabled={busy} onClick={()=>act(kind==='expense'?'record_expense_claim':'pay_salary_advance',{p_id:r.id})}>{kind==='expense'?'XÁC NHẬN & GHI SỔ':'XÁC NHẬN ĐÃ CHI'}</button>}</article>)}</section>}
