import React, { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabaseClient';
import { listOrdersV2 } from '../lib/featureFlags';
import { useAuth } from '../lib/AuthContext';
import UserAvatar from '../components/UserAvatar';
import ShiftTodayCard from '../components/ShiftTodayCard';

const roleName={owner:'Giám đốc Kinh doanh',admin:'Quản lý',cashier:'Thu ngân',kitchen_lead:'Bếp trưởng',kitchen_deputy:'Bếp phó',kitchen:'Thợ làm bánh',bakery:'Nhân viên Bakery',shipper:'Nhân viên vận tải',warehouse:'Nhân viên kho'};
const isDirector=p=>['owner','admin'].includes(p?.role), isLead=p=>p?.role==='kitchen_lead'||(p?.extra_roles||[]).includes('kitchen_lead');

export default function MobileHomeScreen({onNavigate}){
 const {profile}=useAuth(); const [tasks,setTasks]=useState([]),[orders,setOrders]=useState([]),[staff,setStaff]=useState([]),[unread,setUnread]=useState(0);
 useEffect(()=>{Promise.all([supabase.from('my_task_queue').select('*').in('status',['open','in_progress']).order('deadline').limit(6),listOrdersV2().catch(()=>[]),supabase.from('profiles').select('id,full_name,role,station,active').eq('active',true).limit(5),supabase.from('notifications').select('*',{count:'exact',head:true}).eq('is_read',false)]).then(([t,o,s,n])=>{if(!t.error)setTasks(t.data||[]);setOrders(Array.isArray(o)?o:[]);if(!s.error)setStaff(s.data||[]);if(!n.error)setUnread(n.count||0)});},[profile?.id]);
 const counts=useMemo(()=>({total:orders.length,making:orders.filter(o=>['awaiting_acceptance','in_production'].includes(o.status_v2)).length,shipping:orders.filter(o=>['ready_for_fulfillment','in_delivery'].includes(o.status_v2)).length,done:orders.filter(o=>o.status_v2==='completed').length,cancel:orders.filter(o=>o.status_v2==='cancelled').length}),[orders]);
 const canCreate=['owner','admin','cashier','sale','kitchen_lead'].includes(profile?.role)||(profile?.extra_roles||[]).some(r=>['owner','admin','cashier','sale','kitchen_lead'].includes(r));
 const createOrder=()=>{onNavigate('orders');setTimeout(()=>window.dispatchEvent(new Event('sumi-create-order')),0)};
 return <div className="sumi-mobile-page"><header className="sumi-topbar"><div className="sumi-brand"><div className="sumi-brand-mark"><img src="/sumi-bakery-logo.png" alt="Sumi Bakery" /></div><div><div className="sumi-brand-name">SUMI BAKERY</div><div className="sumi-hello">Chào {profile?.full_name||'nhân viên'}</div></div></div><div className="sumi-top-actions"><button className="sumi-bell" onClick={()=>onNavigate('inbox')} aria-label="Thông báo">🔔{unread>0&&<b>{unread}</b>}</button><button className="sumi-avatar-button" onClick={()=>onNavigate('profile')} aria-label="Mở hồ sơ cá nhân"><UserAvatar profile={profile} size={44}/></button></div></header><main className="sumi-main"><PinnedAnnouncement onOpen={()=>onNavigate('feed')}/>{isDirector(profile)?<DirectorHome counts={counts} staff={staff} onNavigate={onNavigate}/>:isLead(profile)?<LeadHome tasks={tasks} onNavigate={onNavigate}/>:<EmployeeHome profile={profile} tasks={tasks} canCreate={canCreate} createOrder={createOrder} onNavigate={onNavigate}/>}</main></div>;
}
function PinnedAnnouncement({onOpen}){const[row,setRow]=useState(null);useEffect(()=>{supabase.from('company_feed_posts').select('id,title,body,severity').eq('post_type','announcement').is('deleted_at',null).in('severity',['important','urgent']).order('created_at',{ascending:false}).limit(1).maybeSingle().then(r=>{if(!r.error)setRow(r.data)})},[]);return row?<button className={`sumi-pinned-announcement ${row.severity}`} onClick={onOpen}><span>📢</span><span><strong>{row.title}</strong><small>{row.body}</small></span><em>›</em></button>:null}
function SectionHead({title,value,onClick}){return <div className="sumi-section-head"><span>{title}</span>{onClick?<button onClick={onClick}>{value}</button>:<span>{value}</span>}</div>}
function Status({icon,name,note,value}){return <button><span className="status-icon">{icon}</span><span><strong>{name}</strong><small>{note}</small></span><b>{value}</b></button>}
function DirectorHome({counts,staff,onNavigate}){return <><div className="sumi-workplace">📊 Toàn hệ thống · Hôm nay</div><div className="sumi-period-tabs"><button className="active">Hôm nay</button><button>7 ngày</button><button>Tháng</button><button>Tuỳ chọn</button></div><div className="sumi-money-grid"><div className="revenue"><small>DOANH THU</small><strong>—</strong><span>Dữ liệu tài chính giới hạn</span></div><div className="cost"><small>CHI</small><strong>—</strong><span>Chỉ GĐ được xem</span></div></div><SectionHead title="TÌNH TRẠNG ĐƠN HÀNG" value={`${counts.total} đơn`}/><div className="sumi-status-list"><Status icon="🧾" name="Tổng đơn hàng" note="Tất cả đơn trong thời gian chọn" value={counts.total}/><Status icon="👩‍🍳" name="Đơn đang làm" note="Đang sản xuất hoặc chuẩn bị" value={counts.making}/><Status icon="🛵" name="Chờ/đang vận chuyển" note="Đã xong hoặc đang trên đường" value={counts.shipping}/><Status icon="✅" name="Đơn hoàn thành" note="Đã giao hoặc nhận tại quầy" value={counts.done}/><Status icon="✕" name="Đơn huỷ" note="Có lý do và người xác nhận" value={counts.cancel}/></div><SectionHead title="NHÂN VIÊN" value="Xem tất cả ›" onClick={()=>onNavigate('staff')}/><div className="sumi-staff-list">{staff.slice(0,4).map(p=><button key={p.id} onClick={()=>onNavigate('staff')}><span className="avatar">{p.role==='kitchen_lead'?'👨‍🍳':'👤'}</span><span><strong>{p.full_name}</strong><small>{roleName[p.role]||p.role}{p.station?` · ${p.station}`:''}</small></span><em>SẴN SÀNG</em></button>)}</div><div className="sumi-flow-note">Màn Tổng quan chỉ tổng hợp dữ liệu được phép xem. Đơn trường học không đưa giá vào luồng vận hành.</div></>}
function LeadHome({tasks,onNavigate}){return <><ShiftTodayCard onNavigate={onNavigate}/><div className="sumi-workplace">👨‍🍳 Xưởng 42 · Bếp sản xuất</div><div className="sumi-org-path">Giám đốc Kinh doanh → Bếp trưởng → Bếp phó → Thợ bánh</div><section className="sumi-lead-hero"><small>CA SẢN XUẤT HÔM NAY</small><h1>{tasks.length} việc đang làm</h1><p>Nhận đơn · chia việc · duyệt nhập kho</p></section><div className="sumi-action-grid"><button onClick={()=>onNavigate('orders')}>🧾<span>Đơn được giao cho bếp</span></button><button onClick={()=>onNavigate('tasks')}>👥<span>Giao người thực hiện</span></button><button onClick={()=>onNavigate('warehouse')}>🌾<span>Yêu cầu nguyên liệu</span></button><button onClick={()=>onNavigate('tasks')}>✅<span>Duyệt mẻ hoàn thành</span></button></div><SectionHead title="TIẾN ĐỘ SẢN XUẤT" value={`${tasks.length} việc`}/><TaskQueue tasks={tasks}/><div className="sumi-flow-note">Bếp trưởng duyệt “Hoàn thành” thì hệ thống mới nhập kho thành phẩm. Nhân viên báo làm xong chưa tự cộng kho.</div></>}
function EmployeeHome({profile,tasks,canCreate,createOrder,onNavigate}){const next=tasks[0];return <><ShiftTodayCard onNavigate={onNavigate}/><div className="sumi-workplace">🏪 {profile?.station||roleName[profile?.role]||'Nơi làm việc'}</div><div className="sumi-org-path">Giám đốc Kinh doanh → Quản lý trực tiếp → {profile?.full_name||'Nhân viên'}</div><SectionHead title="VIỆC TIẾP THEO" value={`Còn ${tasks.length} việc`}/><article className="sumi-next-card"><div className="head"><span>● {next?.deadline?'LÀM ĐÚNG HẠN':'SẴN SÀNG'}</span><time>{next?.deadline?new Date(next.deadline).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}):'Hôm nay'}</time></div><div className="body"><div className="picture">{next?'🎂':'✅'}</div><h1>{next?.title||'Chưa có việc cần làm'}</h1><p>{next?.description||'Khi có việc mới, điện thoại sẽ báo ngay tại đây.'}</p></div><div className="actions"><button>🖼️ Ảnh mẫu</button><button onClick={()=>onNavigate('tasks')}>✓ {next?'ĐÃ LÀM XONG':'XEM VIỆC'}</button></div></article><h2 className="sumi-quick-title">Làm nhanh</h2><button className="sumi-voice" onClick={()=>onNavigate('tasks')}>🎙️ BẤM ĐỂ NÓI</button><div className="sumi-quick-grid">{canCreate&&<button onClick={createOrder}>🧾<span>Tạo đơn</span></button>}<button>📷<span>Chụp ảnh</span></button><button onClick={()=>onNavigate('tasks')}>✅<span>Việc của tôi</span></button><button onClick={()=>onNavigate('incidents')}>⚠️<span>Báo sự cố</span></button></div><SectionHead title="VIỆC SAU ĐÓ" value={`${Math.max(tasks.length-1,0)} việc`}/><TaskQueue tasks={tasks.slice(1)}/></>}
function TaskQueue({tasks}){return <div className="sumi-task-queue">{tasks.map((t,i)=><button key={t.id}><b>{i+2}</b><span><strong>{t.title}</strong><small>{t.order_code?`Đơn ${t.order_code}`:'Việc trong ngày'}</small></span><em>{t.status==='in_progress'?'ĐANG LÀM':'CHỜ'}</em></button>)}</div>}
