import React, { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabaseClient';
import { listOrdersV2 } from '../lib/featureFlags';
import { useAuth } from '../lib/AuthContext';
import UserAvatar from '../components/UserAvatar';
import ShiftTodayCard from '../components/ShiftTodayCard';

import { ROLE_META, KITCHEN_LEAD_ROLES, getRoleMeta, formatStationLabel } from '../lib/roles';

const isDirector = p => ['owner', 'admin'].includes(p?.role);
const isLead = p => KITCHEN_LEAD_ROLES.includes(p?.role) || (p?.extra_roles || []).some(r => KITCHEN_LEAD_ROLES.includes(r));
const getRoleLabel = (r, s) => getRoleMeta(r, s)?.label || r;

export default function MobileHomeScreen({onNavigate}){
 const {profile}=useAuth(); const [tasks,setTasks]=useState([]),[orders,setOrders]=useState([]),[staff,setStaff]=useState([]),[unread,setUnread]=useState(0);
 useEffect(()=>{const run=()=>supabase.rpc('enqueue_order_operational_alerts');run();const timer=setInterval(run,300000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{Promise.all([supabase.from('my_task_queue').select('*').in('status',['open','in_progress']).order('deadline').limit(6),listOrdersV2().catch(()=>[]),supabase.from('profiles').select('id,full_name,role,station,active').eq('active',true).limit(5),supabase.from('notifications').select('*',{count:'exact',head:true}).eq('is_read',false)]).then(([t,o,s,n])=>{if(!t.error)setTasks(t.data||[]);setOrders(Array.isArray(o)?o:[]);if(!s.error)setStaff(s.data||[]);if(!n.error)setUnread(n.count||0)});},[profile?.id]);
 const counts=useMemo(()=>({
  total:orders.length,
  waiting:orders.filter(o=>['awaiting_assignment','awaiting_acceptance'].includes(o.status_v2)&&!o.is_overdue).length,
  production:orders.filter(o=>o.status_v2==='in_production'&&!o.is_overdue).length,
  ready:orders.filter(o=>o.status_v2==='ready_for_fulfillment'&&!o.is_overdue).length,
  delivery:orders.filter(o=>o.status_v2==='in_delivery'&&!o.is_overdue).length,
  completed:orders.filter(o=>o.status_v2==='completed').length,
  overdue:orders.filter(o=>Boolean(o.is_overdue)).length,
 }),[orders]);
 const canCreate=['owner','admin','cashier','sale','kitchen_lead'].includes(profile?.role)||(profile?.extra_roles||[]).some(r=>['owner','admin','cashier','sale','kitchen_lead'].includes(r));
 const createOrder=()=>{onNavigate('orders');setTimeout(()=>window.dispatchEvent(new Event('sumi-create-order')),0)};
 return <div className="sumi-mobile-page"><header className="sumi-topbar"><div className="sumi-brand"><div className="sumi-brand-mark"><img src="/sumi-bakery-logo.png" alt="Sumi Bakery" /></div><div><div className="sumi-brand-name">SUMI BAKERY</div><div className="sumi-hello">Chào {profile?.full_name||'nhân viên'}</div></div></div><div className="sumi-top-actions"><button className="sumi-bell" onClick={()=>onNavigate('inbox')} aria-label="Thông báo">🔔{unread>0&&<b>{unread}</b>}</button><button className="sumi-avatar-button" onClick={()=>onNavigate('profile')} aria-label="Mở hồ sơ cá nhân"><UserAvatar profile={profile} size={44}/></button></div></header><main className="sumi-main"><PinnedAnnouncement onOpen={()=>onNavigate('feed')}/>{isDirector(profile)?<DirectorHome counts={counts} staff={staff} onNavigate={onNavigate}/>:isLead(profile)?<LeadHome tasks={tasks} onNavigate={onNavigate}/>:<EmployeeHome profile={profile} tasks={tasks} canCreate={canCreate} createOrder={createOrder} onNavigate={onNavigate}/>}</main></div>;
}
function PinnedAnnouncement({onOpen}){const[row,setRow]=useState(null);useEffect(()=>{supabase.from('company_feed_posts').select('id,title,body,severity').eq('post_type','announcement').is('deleted_at',null).in('severity',['important','urgent']).order('created_at',{ascending:false}).limit(1).maybeSingle().then(r=>{if(!r.error)setRow(r.data)})},[]);return row?<button className={`sumi-pinned-announcement ${row.severity}`} onClick={onOpen}><span>📢</span><span><strong>{row.title}</strong><small>{row.body}</small></span><em>›</em></button>:null}
function SectionHead({title,value,onClick}){return <div className="sumi-section-head"><span>{title}</span>{onClick?<button onClick={onClick}>{value}</button>:<span>{value}</span>}</div>}
function DirectorHome({counts,staff,onNavigate}){const open=filter=>{onNavigate('orders');setTimeout(()=>window.dispatchEvent(new CustomEvent('sumi-order-filter',{detail:{filter}})),0)};const staffWork=p=>{sessionStorage.setItem('sumi_managed_staff_id',p.id);onNavigate('tasks')};return <><div className="sumi-workplace">📊 Toàn hệ thống · Hôm nay</div><div className="sumi-period-tabs"><button className="active">Hôm nay</button><button>7 ngày</button><button>Tháng</button><button>Tuỳ chọn</button></div><div className="sumi-money-grid"><div className="revenue"><small>DOANH THU</small><strong>—</strong><span>Dữ liệu tài chính giới hạn</span></div><div className="cost"><small>CHI</small><strong>—</strong><span>Chỉ GĐ được xem</span></div></div><SectionHead title="TÌNH TRẠNG ĐƠN HÀNG" value={`${counts.total} đơn`} onClick={()=>open(null)}/><div className="mock-order-overview"><button onClick={()=>open('waiting')}><span>📥</span><strong>Đơn chờ làm</strong><b>{counts.waiting}</b></button><button onClick={()=>open('production')}><span>👩‍🍳</span><strong>Bếp đang làm</strong><b>{counts.production}</b></button><button onClick={()=>open('ready')}><span>📦</span><strong>Chờ vận chuyển</strong><b>{counts.ready}</b></button><button onClick={()=>open('delivery')}><span>🛵</span><strong>Đang vận chuyển</strong><b>{counts.delivery}</b></button><button onClick={()=>open('completed')}><span>✅</span><strong>Giao thành công</strong><b>{counts.completed}</b></button><button onClick={()=>open('overdue')}><span>⚠️</span><strong>Chưa thực hiện</strong><b>{counts.overdue}</b></button></div><SectionHead title="NHÂN VIÊN" value="Xem tất cả ›" onClick={()=>onNavigate('staff')}/><div className="sumi-staff-list">{staff.slice(0,4).map(p=><button key={p.id} onClick={()=>staffWork(p)}><span className="avatar">{KITCHEN_LEAD_ROLES.includes(p.role)?'👨‍🍳':'👤'}</span><span><strong>{p.full_name}</strong><small>{getRoleLabel(p.role)}{p.station?` · ${p.station}`:''}</small></span><em>XEM VIỆC</em></button>)}</div><div className="sumi-flow-note">Bấm nhân viên để giao việc, theo dõi tiến độ và xem báo cáo công việc của người đó.</div></>}
function LeadHome({tasks,onNavigate}){return <><ShiftTodayCard onNavigate={onNavigate}/><div className="sumi-workplace">👨‍🍳 Xưởng sản xuất bánh SUMI</div><div className="sumi-org-path">Giám đốc → Bếp trưởng → Bếp phó → Thợ bánh</div><section className="sumi-lead-hero"><small>CA SẢN XUẤT HÔM NAY</small><h1>{tasks.length} việc đang làm</h1><p>Nhận đơn · chia việc · duyệt hoàn thành</p></section><div className="sumi-action-grid"><button onClick={()=>onNavigate('orders')}>🧾<span>Đơn được giao cho bếp</span></button><button onClick={()=>onNavigate('tasks')}>👥<span>Giao người thực hiện</span></button><button onClick={()=>onNavigate('warehouse')}>🌾<span>Yêu cầu nguyên liệu</span></button><button onClick={()=>onNavigate('tasks')}>✅<span>Duyệt mẻ hoàn thành</span></button></div><SectionHead title="TIẾN ĐỘ SẢN XUẤT" value={`${tasks.length} việc`}/><TaskQueue tasks={tasks}/><div className="sumi-flow-note">Bếp trưởng duyệt “Hoàn thành” thì hệ thống mới nhập kho thành phẩm. Nhân viên báo làm xong chưa tự cộng kho.</div></>}
function EmployeeHome({profile,tasks,canCreate,createOrder,onNavigate}){const next=tasks[0];return <><ShiftTodayCard onNavigate={onNavigate}/><div className="sumi-workplace">🏪 {profile?.station||getRoleLabel(profile?.role)||'Nơi làm việc'}</div><div className="sumi-org-path">Giám đốc Kinh doanh → Quản lý trực tiếp → {profile?.full_name||'Nhân viên'}</div><SectionHead title="VIỆC TIẾP THEO" value={`Còn ${tasks.length} việc`}/><article className="sumi-next-card"><div className="head"><span>● {next?.deadline?'LÀM ĐÚNG HẠN':'SẴN SÀNG'}</span><time>{next?.deadline?new Date(next.deadline).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}):'Hôm nay'}</time></div><div className="body"><div className="picture">{next?'🎂':'✅'}</div><h1>{next?.title||'Chưa có việc cần làm'}</h1><p>{next?.description||'Khi có việc mới, điện thoại sẽ báo ngay tại đây.'}</p></div><div className="actions"><button>🖼️ Ảnh mẫu</button><button onClick={()=>onNavigate('tasks')}>✓ {next?'ĐÃ LÀM XONG':'XEM VIỆC'}</button></div></article><h2 className="sumi-quick-title">Làm nhanh</h2><button className="sumi-voice" onClick={()=>onNavigate('tasks')}>🎙️ BẤM ĐỂ NÓI</button><div className="sumi-quick-grid">{canCreate&&<button onClick={createOrder}>🧾<span>Tạo đơn</span></button>}<button>📷<span>Chụp ảnh</span></button><button onClick={()=>onNavigate('tasks')}>✅<span>Việc của tôi</span></button><button onClick={()=>onNavigate('incidents')}>⚠️<span>Báo sự cố</span></button></div><SectionHead title="VIỆC SAU ĐÓ" value={`${Math.max(tasks.length-1,0)} việc`}/><TaskQueue tasks={tasks.slice(1)}/></>}
function TaskQueue({tasks}){return <div className="sumi-task-queue">{tasks.map((t,i)=><button key={t.id}><b>{i+2}</b><span><strong>{t.title}</strong><small>{t.order_code?`Đơn ${t.order_code}`:'Việc trong ngày'}</small></span><em>{t.status==='in_progress'?'ĐANG LÀM':'CHỜ'}</em></button>)}</div>}
