import React,{useEffect,useState}from'react';import{supabase}from'../lib/supabaseClient';import{useAuth}from'../lib/AuthContext';import{VoiceMicButton}from'../components/VoiceMicButton';
const button={minHeight:52,border:0,borderRadius:14,padding:'0 16px',fontSize:17,fontWeight:900};
const gps=()=>new Promise((resolve,reject)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude}),reject,{enableHighAccuracy:true,timeout:15000}):reject(new Error('Điện thoại không hỗ trợ định vị')));
export default function ShippingV2Screen(){const{profile}=useAuth();const[runs,setRuns]=useState([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const manager=['owner','admin','transport_lead'].some(r=>r===profile?.role||(profile?.extra_roles||[]).includes(r));
 const load=async()=>{const{data,error}=await supabase.from('delivery_runs').select('id,run_code,status,version,planned_distance_km,started_at,delivery_stops(id,order_id,sequence_no,status,destination_address,delivered_at,orders(order_code,required_at))').order('created_at',{ascending:false});if(error)throw error;setRuns(data||[])};useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const rpc=async(name,args)=>{setBusy(true);setError('');try{const{error}=await supabase.rpc(name,args);if(error)throw error;await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const accept=r=>rpc('accept_delivery_run_v2',{p_idempotency_key:crypto.randomUUID(),p_run_id:r.id,p_expected_version:r.version});
 const start=async r=>{try{const p=await gps();await rpc('start_delivery_run_v2',{p_idempotency_key:crypto.randomUUID(),p_run_id:r.id,p_expected_version:r.version,p_lat:p.lat,p_lng:p.lng})}catch(e){setError(e.message||'Không lấy được GPS')}};
 return <div style={{padding:16,maxWidth:760,margin:'0 auto'}}>{manager&&<DispatchPanel onCreated={load} setError={setError}/>}<h2 style={{margin:'0 0 4px'}}>🚚 Chuyến giao của tôi</h2><p style={{marginTop:0,color:'var(--text-muted)'}}>{profile?.full_name}</p>{error&&<div style={{padding:12,borderRadius:12,background:'#fee',color:'#b42318',marginBottom:10}}>{error}</div>}
 {runs.map(r=><div key={r.id} style={{padding:16,borderRadius:20,background:'var(--surface-card)',border:'1px solid var(--border-default)',marginBottom:14}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><strong style={{fontSize:19}}>{r.run_code}</strong><span style={{fontWeight:800}}>{r.status}</span></div><div style={{margin:'8px 0'}}>{r.delivery_stops?.length||0} điểm · {r.planned_distance_km??'—'} km dự kiến</div>
  {r.status==='planned'&&<button disabled={busy} onClick={()=>accept(r)} style={{...button,width:'100%',background:'var(--brand-primary)',color:'white'}}>Nhận chuyến</button>}{r.status==='accepted'&&<button disabled={busy} onClick={()=>start(r)} style={{...button,width:'100%',background:'#087f5b',color:'white'}}>📍 Bắt đầu giao</button>}
  {r.delivery_stops?.sort((a,b)=>a.sequence_no-b.sequence_no).map(s=><StopCard key={s.id} stop={s} runActive={r.status==='in_transit'} onDone={load} setError={setError}/>)}</div>)}
 {!runs.length&&<div style={{padding:30,textAlign:'center',color:'var(--text-muted)'}}>Chưa có chuyến giao được phân</div>}</div>}
function DispatchPanel({onCreated,setError}){const[open,setOpen]=useState(false);const[orders,setOrders]=useState([]);const[drivers,setDrivers]=useState([]);const[selected,setSelected]=useState([]);const[driver,setDriver]=useState('');const[km,setKm]=useState('');const[busy,setBusy]=useState(false);
 const load=async()=>{const[o,d]=await Promise.all([supabase.from('order_operations_list').select('id,order_code,address,required_at,status_v2').eq('status_v2','ready_for_fulfillment').order('required_at'),supabase.from('profiles').select('id,full_name,role,extra_roles').eq('approved',true).eq('active',true)]);if(o.error)throw o.error;if(d.error)throw d.error;setOrders(o.data||[]);setDrivers((d.data||[]).filter(x=>x.role==='shipper'||(x.extra_roles||[]).includes('shipper')))};useEffect(()=>{if(open)load().catch(e=>setError(e.message))},[open]);
 const create=async()=>{setBusy(true);setError('');try{if(!selected.length)throw new Error('Chọn ít nhất một đơn');if(!driver)throw new Error('Chọn tài xế');const{error}=await supabase.rpc('create_delivery_run_v2',{p_idempotency_key:crypto.randomUUID(),p_driver_id:driver,p_order_ids:selected,p_planned_distance_km:km?Number(km):null});if(error)throw error;setOpen(false);setSelected([]);await onCreated()}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(!open)return <button onClick={()=>setOpen(true)} style={{...button,width:'100%',marginBottom:14,background:'var(--brand-primary)',color:'white'}}>＋ Tạo chuyến giao</button>;
 return <div style={{padding:16,borderRadius:20,background:'var(--surface-card)',border:'2px solid var(--brand-primary)',marginBottom:16}}><div style={{display:'flex',justifyContent:'space-between'}}><h3 style={{margin:0}}>Điều phối chuyến</h3><button onClick={()=>setOpen(false)} style={{border:0,background:'none',fontSize:24}}>×</button></div><p>Chỉ hiển thị đơn đã đủ hàng hoặc được duyệt giao một phần.</p><div style={{maxHeight:260,overflowY:'auto'}}>{orders.map(o=><label key={o.id} style={{display:'flex',gap:10,padding:'10px 0',borderBottom:'1px solid var(--border-default)'}}><input type="checkbox" checked={selected.includes(o.id)} onChange={e=>setSelected(x=>e.target.checked?[...x,o.id]:x.filter(id=>id!==o.id))}/><span><b>{o.order_code}</b><br/><small>{o.address||'Nhận tại quầy'} · {o.required_at?new Date(o.required_at).toLocaleString('vi-VN'):'Chưa có giờ'}</small></span></label>)}</div>{!orders.length&&<p style={{color:'var(--text-muted)'}}>Chưa có đơn chờ giao.</p>}<select value={driver} onChange={e=>setDriver(e.target.value)} style={{width:'100%',minHeight:50,borderRadius:12,marginTop:10}}><option value="">Chọn tài xế</option>{drivers.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select><input type="number" min="0" step="0.1" value={km} onChange={e=>setKm(e.target.value)} placeholder="Km kế hoạch (có thể bổ sung sau)" style={{width:'100%',boxSizing:'border-box',minHeight:50,borderRadius:12,padding:10,marginTop:8}}/><button disabled={busy||!selected.length||!driver} onClick={create} style={{...button,width:'100%',marginTop:10,background:'#087f5b',color:'white'}}>Tạo chuyến · {selected.length} đơn</button></div>}
function StopCard({stop,runActive,onDone,setError}){const{profile}=useAuth();const[recipient,setRecipient]=useState('');const[file,setFile]=useState(null);const[busy,setBusy]=useState(false);const done=async()=>{setBusy(true);setError('');try{if(!file)throw new Error('Cần chụp ảnh giao hàng');if(!recipient.trim())throw new Error('Cần nhập người nhận');const p=await gps();const path=`orders/${stop.order_id}/delivery/${crypto.randomUUID()}-${file.name}`;let r=await supabase.storage.from('uploads').upload(path,file);if(r.error)throw r.error;r=await supabase.from('order_attachments').insert({order_id:stop.order_id,attachment_type:'delivery_proof',storage_path:path,mime_type:file.type,size_bytes:file.size,created_by:profile.id,gps_lat:p.lat,gps_lng:p.lng}).select('id').single();if(r.error)throw r.error;const x=await supabase.rpc('complete_delivery_stop',{p_idempotency_key:crypto.randomUUID(),p_stop_id:stop.id,p_proof_attachment_id:r.data.id,p_lat:p.lat,p_lng:p.lng,p_recipient:recipient.trim()});if(x.error)throw x.error;await onDone()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const map=stop.destination_address?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(stop.destination_address)}`:'#';return <div style={{marginTop:12,padding:12,borderRadius:16,background:'var(--surface-app)',border:'1px solid var(--border-default)'}}><div style={{display:'flex',justifyContent:'space-between'}}><b>Điểm {stop.sequence_no} · {stop.orders?.order_code}</b><span>{stop.status==='delivered'?'✅ Đã giao':''}</span></div><div style={{margin:'8px 0'}}>{stop.destination_address||'Chưa có địa chỉ'}</div>{stop.status!=='delivered'&&runActive&&<><a href={map} target="_blank" rel="noreferrer" style={{display:'grid',placeItems:'center',...button,background:'#e7f5ff',color:'#075985',textDecoration:'none'}}>🗺️ Mở bản đồ</a><div style={{display:'flex',gap:8,marginTop:8}}><input value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="Tên người nhận" style={{flex:1,minHeight:50,borderRadius:12,padding:10,fontSize:17}}/><VoiceMicButton onTranscript={setRecipient}/></div><label style={{display:'grid',placeItems:'center',...button,marginTop:8,background:'#f1f3f5'}}>📷 {file?'Đã chọn ảnh':'Chụp ảnh giao hàng'}<input hidden type="file" accept="image/*" capture="environment" onChange={e=>setFile(e.target.files[0])}/></label><button disabled={busy} onClick={done} style={{...button,width:'100%',marginTop:8,background:'#087f5b',color:'white'}}>✅ Hoàn thành giao</button></>}</div>}
