import React,{useEffect,useMemo,useRef,useState} from 'react';
import {supabase} from '../lib/supabaseClient';
import {useAuth} from '../lib/AuthContext';
import {newId} from '../lib/ids';
import '../visual-guides.css';

const CAT={general:['🧭','Tất cả'],tasks:['✅','Nhân viên'],orders:['🧾','Tạo đơn'],cold:['🍰','Bếp lạnh'],hot:['🥐','Bếp nóng'],macaron:['🌈','Macaron'],packing:['📦','Đóng gói'],delivery:['🛵','Giao hàng'],warehouse:['🏷️','Kho hàng'],accounting:['🧮','Kế toán'],management:['📊','Quản lý']};
const isDirector=p=>['owner','admin'].includes(p?.role)||(p?.extra_roles||[]).some(x=>['owner','admin'].includes(x));
const signed=async path=>{if(!path)return '';if(path.startsWith('/'))return path;const {data}=await supabase.storage.from('uploads').createSignedUrl(path,3600);return data?.signedUrl||''};
const canSeeGuide=(guide,profile)=>{const audience=guide.audience_roles||[];if(!audience.length||isDirector(profile))return true;const roles=[profile?.role,...(profile?.extra_roles||[])].filter(Boolean);return audience.some(role=>roles.includes(role));};
const speak=text=>{if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='vi-VN';u.rate=.82;window.speechSynthesis.speak(u)};

function GuideEditor({profile,onClose,onDone,guide}){
 const [title,setTitle]=useState(guide?.title||''),[summary,setSummary]=useState(guide?.summary||''),[category,setCategory]=useState(guide?.category||'general');
 const [steps,setSteps]=useState(guide?.steps?.length?guide.steps.map(x=>({...x,file:null})): [{title:'',instruction:'',warning_text:'',file:null}]);const[busy,setBusy]=useState(false),[error,setError]=useState('');
 const change=(i,k,v)=>setSteps(s=>s.map((x,n)=>n===i?{...x,[k]:v}:x));
 const save=async()=>{if(!title.trim())return setError('Hãy nhập tên hướng dẫn.');if(steps.some(x=>!x.title.trim()||!x.instruction.trim()))return setError('Mỗi bước cần có tên và nội dung ngắn.');setBusy(true);setError('');try{
  let gid=guide?.id;if(gid){let r=await supabase.from('visual_work_guides').update({title:title.trim(),summary:summary.trim()||null,category,updated_by:profile.id,updated_at:new Date().toISOString(),version:(guide.version||1)+1}).eq('id',gid);if(r.error)throw r.error;r=await supabase.from('visual_work_guide_steps').delete().eq('guide_id',gid);if(r.error)throw r.error;}else{const r=await supabase.from('visual_work_guides').insert({title:title.trim(),summary:summary.trim()||null,category,created_by:profile.id}).select('id').single();if(r.error)throw r.error;gid=r.data.id;}
  const rows=[];for(let i=0;i<steps.length;i++){let path=steps[i].image_storage_path||null;if(steps[i].file){const ext=(steps[i].file.name.split('.').pop()||'jpg').toLowerCase();path=`work-guides/${gid}/step-${i+1}-${newId()}.${ext}`;const r=await supabase.storage.from('uploads').upload(path,steps[i].file);if(r.error)throw r.error;}rows.push({guide_id:gid,step_order:i+1,title:steps[i].title.trim(),instruction:steps[i].instruction.trim(),warning_text:steps[i].warning_text.trim()||null,image_storage_path:path});}
  const r=await supabase.from('visual_work_guide_steps').insert(rows);if(r.error)throw r.error;onDone();
 }catch(e){setError(e.message||'Không thể lưu hướng dẫn.')}finally{setBusy(false)}};
 return <div className="vg-overlay"><section className="vg-editor"><header><button onClick={onClose}>‹</button><div><small>QUẢN LÝ NỘI DUNG</small><h2>{guide?'Sửa hướng dẫn':'Tạo hướng dẫn mới'}</h2></div></header><label>Tên hướng dẫn<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ví dụ: Đóng hộp macaron 12 màu"/></label><label>Mô tả ngắn<textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Nhân viên sẽ biết mình sắp làm gì"/></label><label>Nhóm thao tác<select value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(CAT).filter(([k])=>k!=='general').map(([k,v])=><option value={k} key={k}>{v[1]}</option>)}</select></label><h3>Các bước bằng hình ảnh</h3>{steps.map((s,i)=><article className="vg-step-edit" key={i}><b>BƯỚC {i+1}</b><input value={s.title} onChange={e=>change(i,'title',e.target.value)} placeholder="Tên bước"/><textarea value={s.instruction} onChange={e=>change(i,'instruction',e.target.value)} placeholder="Một câu ngắn, dễ nghe và dễ làm"/><input value={s.warning_text||''} onChange={e=>change(i,'warning_text',e.target.value)} placeholder="Điều cần tránh (nếu có)"/><label className="vg-photo-pick">📷 {s.file?'Đã chọn ảnh':'Chụp hoặc chọn ảnh'}<input hidden type="file" accept="image/*" capture="environment" onChange={e=>change(i,'file',e.target.files?.[0]||null)}/></label>{steps.length>1&&<button className="vg-remove" onClick={()=>setSteps(x=>x.filter((_,n)=>n!==i))}>Xóa bước này</button>}</article>)}<button className="vg-add-step" onClick={()=>setSteps(x=>[...x,{title:'',instruction:'',warning_text:'',file:null}])}>＋ THÊM BƯỚC</button>{error&&<div className="vg-error">{error}</div>}<button className="vg-save" disabled={busy} onClick={save}>{busy?'ĐANG LƯU...':'LƯU HƯỚNG DẪN'}</button></section></div>
}

function GuidePlayer({guide,profile,onClose,onEdit}){const[i,setI]=useState(0),[urls,setUrls]=useState({}),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');const fileRef=useRef();const step=guide.steps[i];useEffect(()=>{Promise.all(guide.steps.map(async s=>[s.id,await signed(s.image_storage_path)])).then(a=>setUrls(Object.fromEntries(a)))},[guide.id]);const finish=async file=>{setBusy(true);setError('');try{let path=null;if(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();path=`work-guide-results/${guide.id}/${profile.id}/${newId()}.${ext}`;const u=await supabase.storage.from('uploads').upload(path,file);if(u.error)throw u.error;}const r=await supabase.from('visual_work_guide_progress').upsert({guide_id:guide.id,profile_id:profile.id,guide_version:guide.version,last_step:guide.steps.length,completed_at:new Date().toISOString(),result_storage_path:path,updated_at:new Date().toISOString()},{onConflict:'guide_id,profile_id'});if(r.error)throw r.error;setDone(true)}catch(e){setError(e.message||'Không thể xác nhận hoàn thành.')}finally{setBusy(false)}};return <div className="vg-overlay"><section className="vg-player"><header><button onClick={onClose}>×</button><div><small>{CAT[guide.category]?.[1]||'Hướng dẫn'}</small><h2>{guide.title}</h2></div>{onEdit&&<button onClick={onEdit}>✏️</button>}</header>{done?<div className="vg-finished"><span>✅</span><h2>Đã hoàn thành hướng dẫn</h2><p>Ảnh kết quả đã được lưu để quản lý kiểm tra.</p><button onClick={onClose}>XONG</button></div>:<><div className="vg-progress"><b>BƯỚC {i+1}/{guide.steps.length}</b><i><span style={{width:`${((i+1)/guide.steps.length)*100}%`}}/></i></div><div className="vg-picture">{urls[step.id]?<img src={urls[step.id]} alt={step.title}/>:<span>📷</span>}</div><div className="vg-instruction"><small>BƯỚC {i+1}</small><h1>{step.title}</h1><p>{step.instruction}</p>{step.warning_text&&<aside>⚠️ {step.warning_text}</aside>}<button onClick={()=>speak(`${step.title}. ${step.instruction}. ${step.warning_text||''}`)}>🔊 NGHE HƯỚNG DẪN</button></div><div className="vg-player-actions">{i>0&&<button onClick={()=>setI(i-1)}>‹ QUAY LẠI</button>}{i<guide.steps.length-1?<button className="next" onClick={()=>setI(i+1)}>ĐÃ HIỂU · TIẾP ›</button>:<button className="next" onClick={()=>fileRef.current?.click()}>📷 CHỤP KẾT QUẢ</button>}</div>{i===guide.steps.length-1&&<><input ref={fileRef} hidden type="file" accept="image/*" capture="environment" onChange={e=>finish(e.target.files?.[0])}/><button className="vg-no-photo" disabled={busy} onClick={()=>finish(null)}>Hoàn thành không cần ảnh</button></>}{error&&<div className="vg-error">{error}</div>}</>}</section></div>}

export default function VisualGuidesScreen(){const{profile}=useAuth();const[guides,setGuides]=useState([]),[category,setCategory]=useState('general'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(null),[editing,setEditing]=useState(null);const director=isDirector(profile);const load=async()=>{setLoading(true);setError('');const r=await supabase.from('visual_work_guides').select('*,visual_work_guide_steps(*)').is('deleted_at',null).order('updated_at',{ascending:false});if(r.error)setError('Chưa tải được hướng dẫn. Hãy thử lại.');else setGuides((r.data||[]).filter(g=>canSeeGuide(g,profile)).map(g=>({...g,steps:(g.visual_work_guide_steps||[]).sort((a,b)=>a.step_order-b.step_order)})));setLoading(false)};useEffect(()=>{load()},[profile?.id]);const shown=useMemo(()=>guides.filter(g=>category==='general'||g.category===category),[guides,category]);return <main className="vg-page"><header className="vg-hero"><div><small>SUMI · LÀM ĐÚNG NGAY TỪ ĐẦU</small><h1>Nhìn ảnh là làm được</h1><p>Chọn việc, xem từng bước và bấm nghe nếu khó đọc.</p></div><span>👆</span></header>{director&&<button className="vg-create" onClick={()=>setEditing({new:true})}>＋ TẠO HƯỚNG DẪN</button>}<nav className="vg-cats">{Object.entries(CAT).filter(([k])=>k==='general'||guides.some(g=>g.category===k)).map(([k,v])=><button key={k} className={category===k?'active':''} onClick={()=>setCategory(k)}>{v[0]} {v[1]}</button>)}</nav>{loading?<div className="vg-empty">Đang tải hướng dẫn...</div>:error?<div className="vg-error">{error}<button onClick={load}>Thử lại</button></div>:shown.length?<section className="vg-grid">{shown.map(g=><button className="vg-card" key={g.id} onClick={()=>setOpen(g)}><span>{CAT[g.category]?.[0]||'🧭'}</span><div><small>{CAT[g.category]?.[1]||'Công việc'} · {g.steps.length} bước</small><h2>{g.title}</h2><p>{g.summary||'Xem ảnh và làm lần lượt từng bước.'}</p></div><b>›</b></button>)}</section>:<div className="vg-empty"><span>🖼️</span><h2>Chưa có hướng dẫn</h2><p>{director?'Bấm “Tạo hướng dẫn” để thêm bộ ảnh đầu tiên.':'Quản lý đang chuẩn bị nội dung hướng dẫn.'}</p></div>}{open&&<GuidePlayer guide={open} profile={profile} onClose={()=>setOpen(null)} onEdit={director?()=>{setEditing(open);setOpen(null)}:null}/>} {editing&&<GuideEditor profile={profile} guide={editing.new?null:editing} onClose={()=>setEditing(null)} onDone={()=>{setEditing(null);load()}}/>}</main>}
