import React,{useEffect,useState} from 'react';import{supabase}from'../lib/supabaseClient';import{useAuth}from'../lib/AuthContext';import{VoiceMicButton}from'./VoiceMicButton';
const btn={minHeight:46,border:0,borderRadius:12,padding:'0 14px',fontWeight:800};
export default function PackageTaskPanel({packageId,onChanged}){const{profile}=useAuth();const[tasks,setTasks]=useState([]);const[staff,setStaff]=useState([]);const[assignee,setAssignee]=useState('');const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const lead=['owner','admin','kitchen_lead','kitchen_deputy'].some(r=>r===profile?.role||(profile?.extra_roles||[]).includes(r));
 const load=async()=>{const[t,p]=await Promise.all([supabase.from('tasks').select('id,title,description,status,assignee_id,started_at,completed_at,version,required_proof_types,profiles!tasks_assignee_id_fkey(full_name)').eq('work_package_id',packageId).order('created_at'),supabase.from('profiles').select('id,full_name').eq('approved',true).eq('active',true).order('full_name')]);if(t.error)throw t.error;setTasks(t.data||[]);setStaff(p.data||[]);};useEffect(()=>{load().catch(e=>setError(e.message));},[packageId]);
 const rpc=async(name,args)=>{setBusy(true);setError('');try{const{error}=await supabase.rpc(name,args);if(error)throw error;await load();onChanged?.();}catch(e){setError(e.message)}finally{setBusy(false)}};
 const assign=()=>rpc('assign_package_task',{p_idempotency_key:crypto.randomUUID(),p_package_id:packageId,p_assignee_id:assignee,p_title:title,p_description:description||null,p_deadline:null,p_required_proof_types:['photo']});
 const proof=async(t,file)=>{setBusy(true);try{const path=`tasks/${t.id}/${crypto.randomUUID()}-${file.name}`;let r=await supabase.storage.from('uploads').upload(path,file);if(r.error)throw r.error;r=await supabase.from('task_proofs').insert({task_id:t.id,proof_type:'photo',storage_path:path,created_by:profile.id});if(r.error)throw r.error;await load();}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div><strong>✅ Việc trong phần đơn</strong>{tasks.map(t=><div key={t.id} style={{padding:'10px 0',borderBottom:'1px solid var(--border-default)'}}><b>{t.title}</b> · {t.profiles?.full_name||'Chưa rõ'}<div>{t.status==='done'?'Đã hoàn thành':t.started_at?'Đang làm':'Chưa bắt đầu'}</div>{t.assignee_id===profile?.id&&t.status!=='done'&&<div style={{display:'flex',gap:8,marginTop:8,flexWrap:'wrap'}}>{!t.started_at&&<button style={btn} disabled={busy} onClick={()=>rpc('start_task_v2',{p_idempotency_key:crypto.randomUUID(),p_task_id:t.id,p_expected_version:t.version})}>▶ Bắt đầu</button>}<label style={{...btn,display:'grid',placeItems:'center',background:'#eee'}}>📷 Gửi ảnh<input hidden type="file" accept="image/*" capture="environment" onChange={e=>e.target.files[0]&&proof(t,e.target.files[0])}/></label><button style={{...btn,background:'#087f5b',color:'white'}} disabled={busy} onClick={()=>rpc('complete_task_v2',{p_idempotency_key:crypto.randomUUID(),p_task_id:t.id,p_expected_version:t.version,p_note:null})}>Hoàn thành</button></div>}</div>)}
 {lead&&<div style={{marginTop:12,display:'grid',gap:8}}><select value={assignee} onChange={e=>setAssignee(e.target.value)} style={{minHeight:48,borderRadius:12}}><option value="">Chọn nhân viên</option>{staff.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nội dung việc" style={{minHeight:48,borderRadius:12,padding:10}}/><div style={{display:'flex',gap:8}}><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Mô tả hoặc bấm Nói" style={{flex:1,minHeight:48,borderRadius:12,padding:10}}/><VoiceMicButton onTranscript={x=>setDescription(x)}/></div><button style={{...btn,background:'var(--brand-primary)',color:'white'}} disabled={!assignee||!title||busy} onClick={assign}>Giao việc</button></div>}{error&&<div style={{color:'#b42318'}}>{error}</div>}</div>}
